### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by Mateleo** [JoelBesada/spacetime#2]
Hi,
I love your extension, but it may be good to export our data to json or csv

**Comment by VampireChicken12** [comment]
@Mateleo old issue but the fork I made adds this feature and a few more.

**Comment by Mateleo** [comment]
@VampireChicken12 Haha, thanks for this! I'm glad you took the time to respond.

**Comment by VampireChicken12** [comment]
> @VampireChicken12 Haha, thanks for this! I'm glad you took the time to respond.

No problem

**Comment by joshuaiz** [comment]
@VampireChicken12 Came here for this feature. What is the best way to install your fork?

**Comment by VampireChicken12** [comment]
@joshuaiz 
1. **Clone the Repository**:
   ```bash
   git clone https://github.com/VampireChicken12/spacetime.git
   cd <your-cloned-repo-name>
   ```

2. **Install dependencies**:
   ```bash
   npm install
   ```

3. **Install VSCE**:
   ```bash
   npm install -g @vscode/vsce
   ```

4. **Package the Extension**:
   ```bash
   vsce package
   ```

5. **Install in VSCode**:
   - Open VSCode.
   - Press `Ctrl + Shift + P` (or `Cmd + Shift + P` on macOS).
   - Type `Extensions: Install from VSIX` and select the generated `.vsix` file.

**Comment by joshuaiz** [comment]
@VampireChicken12 thanks so much.

I think there's one step missing before #3 which is `npm install` but I figured it out and got it installed!

**Comment by VampireChicken12** [comment]
> @VampireChicken12 thanks so much.
> 
> I think there's one step missing before #3 which is `npm install` but I figured it out and got it installed!

oh my bad I'll edit my message

**Comment by VampireChicken12** [comment]
@joshuaiz no problem
